# Generated by Django 5.2.1 on 2025-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tvoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eco2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
